version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  php:
    build: ./php
    container_name: wp_php
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - wp-network

  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: wp_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - php
    networks:
      - wp-network
  
  wpcli:
    image: wordpress:cli
    container_name: wp_cli
    depends_on:
      - db
      - wordpress
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
